# Generated by Django 5.0.1 on 2024-01-27 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("decription", models.CharField(max_length=200)),
                ("creation_time", models.DateTimeField(auto_now=True)),
                ("completion_time", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CREATED", "created"),
                            ("INPROGRESS", "inprogress"),
                            ("completed", "completed"),
                        ],
                        default="CREATED",
                        max_length=50,
                    ),
                ),
            ],
        ),
    ]
