# Generated by Django 5.0.1 on 2024-01-27 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="decription",
            new_name="description",
        ),
    ]
