# Generated by Django 5.0.1 on 2024-01-27 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_rename_decription_task_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="name",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
