# Generated by Django 5.0.1 on 2024-01-27 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_task_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["creation_time"]},
        ),
    ]
